#!/bin/bash
# test parse params
(( ii = 0 ))
while read LINE || [ -n "$LINE" ]; do 
	(( ii = ii + 1 ))
	echo "'${LINE}'" #$ii - 
	#echo "${LINE:0:1}"
	[ "${LINE:0:1}" == "#" ] && LINE=""
	#echo "${LINE%%" #"*}"
	if [ "$LINE" != "" ]; then
		LINE="${LINE%%" #"*}" # before ' #' -  longest match from back
		#trimmed=$([[ "$LINE" =~ [[:space:]]*([^[:space:]]|[^[:space:]].*[^[:space:]])[[:space:]]* ]]; echo -n "${BASH_REMATCH[1]}")
		LINE="${LINE%"${LINE##*[![:space:]]}"}" #  remove trailing whitespace "
		#echo "  => '$LINE'"
		VAR="${LINE%%"="*}" # before '='
		#echo "  => '$VAR'"
		VAL="${LINE#*=}" # after '='
		echo "  => '$VAR' = '$VAL'"
	  fi
  done < t5.txt | tr -d '\r'