#!/bin/bash 
# -x
# pren <prj> [<list>] - upd path of prj (find prj by name)
# pren -n=<prj> -p=<path> -t=<type> -r=<remote> -s=<set>

# TODO: case 1

prj_name=$1
#[[ "$prj_name" == "" ]] && echo -e "${red}[PROJECT MOVE] Project name is missed !${norm}" && exit
#list=$2

#new_path=$(pwd) #; echo new_path: $new_path
curr_path="${PWD/#$HOME/~}" # replace $HOME to ~

# TODO: detect repo type (git/svn/hg - .git foder / .svn folder? / ..) and exit if new_path not a repo 

. lib-prj
home=$(home) # echo home: $home
host=$(host) # echo host: $host

if [[ "$list" == "" ]]; then
	prj_list=$(get_repos).list 
  else
  	prj_list="$list.list"
  fi
# echo "prj_list: $prj_list"
# TODO: test prj in list
#exit

[[ ! -f "$home/.cfg/$host/$prj_name" ]] && echo -e "${red}[PROJECT MOVE] Project file not found (by name) !${norm}" && exit
#echo sed -i '' -E "'s/^(path=)(.*)/\1${curr_path//\//\\/}/g'" "$home/.cfg/$host/$prj_name" #;  exit 
sed -i -E "s/^(path=)(.*)/\1${curr_path//\//\\/}/g" "$home/.cfg/$host/$prj_name" || exit 

plist

