:toc:
:toc-title:

= UTILS-PRJ

== What for

utils-prj is a set of shell scripts for:

	* rapid control dozens of projects in different contexts
		** define and switch context (cmd: psw <context>). Context describes set of project
		** go to project home folder. Project points to some folder (ex git repo)
		** bulk operation with context projects or overall (like review state of all projects in context, pull or fix changes, full sync with remotes)
	* simple way to change current folder in terminal using project alias (ex. 'padd prj1' will add alias for current folder and 'pgo prj1' will change current folder)

== Terms

*project* - pointer to project (path, repo type, etc.)

*set* - a group of projects (context), ex. in different context (ex job, my_utils, my_studies, etc.)


== Setup

=== Prerequisites

==== Mandatory:
	* coreutils, one of:
		** msys on Windows, ex:
			*** git 1.7?.5? (msys 32bit)
			*** git 2.0.0 (msys 64bit)
			*** msys
			*** msys2
			*** mingw (msys 32bit)
			*** mingw64
		** bash 3.2??+ (linux ??)
	** gnu-sed (for osx only) (brew install coreutils)

==== Optional:
	* utils-env library - to print colored messages requires (you may don't install them, then messages just willn't in color)
	* utils-git library - to fix in vcs(git) or sync with remotes (bash script library to manupulate of git repositories in simple manner)
		** cmd_state_of_one_project	gis
		** cmd_save_all_projects		gis,gok
		** cmd_save_project_at_local	gac
	* project tools (accessable by PATH var)
		** git
		** rsync (cwRsync) - in dev
		** subversion - in dev

=== How to install

	coreutils
	git

	$ cd <my_utils> # ex cd $HOME
	$ clone ..
	$ setup
	setup 		# it makes configs in user's home within <host_name> subfolder and default set of projects

=== How to uninstall

	$ uninstall-utils-prj


== Ref impl

	cd <project root path>
	padd p1		# add alias 'p1' for your project (and add pwd as projects path)
	plist		# to view your projects in current set (default)
	touch some_file # to make changes in project (it could be manipulation on any file)

	cd -		# change path to another
	pstate p1	# review status of project 'p1'
	pgo p1		# change path to projects path
	pstate .	# review status of current project
	pst		# to view status of all projects in current set (ex. you'll need to pull or push or add&commit you project)
	pfix . 		# add & commit your changes in local repository
	psave . 'ok'	# add, commit and push changes with massage 'ok'
	pget . 		# pull changes from remote

== Sync round

	psta		# view
	pgeta
	psavea
	psw set2
	psta

	psets
	psw
	plist
	pgo


== Command conventions

	next param used for:
	. - current project
	.. - all projects in set
	... - ovarall projects

== Folders / files / content

	.cfg-FOLDER
		<host1>-FOLDER
			default-FILE
				default_list=list1
			<list1>-FILE
				<prj_alias_1>
				<prj_alias_2>
			<list2>-FILE
				<prj_alias_2>
				<prj_alias_3>
			<prj_alias_1>-FILE
				path=msys_or_linux_path/to/root/dir/with/project
				type=git|svn|..
				remote_default=<default_remote_ex_origin>
				remote_extra=<extra_remote_ex_bitbucket>
				remote_extra=<extra_remote_ex_github>
			<prj_alias_2>-FILE
				...
			<prj_alias_3>-FILE
				...
		<host2>-FOLDER-FILE
			default-FILE
				<prj_alias_1>
				<prj_alias_2>
			<list1>-FILE
			<prj_alias_1>-FILE
				...
			<prj_alias_2>-FILE
				...

== Commands & major files

	$ p-help

