== What for
cli utility for 
- to rapid control dozens of projects (switch context to set of projects; go to home project folder; bulk state review, fix and sync)
- use simple mode to fast switch favorite folders

== Setup


== Prerequisites

- to control git projects requires utils-git library (extra shell commands)
	cmd_state_of_one_project	gis
	cmd_save_all_projects		gis,gok
	cmd_save_project_at_local	gac
- requires utils-env library to print colored messages (w/o it will use current color only)
- requires git in PATH for projects of the type

== Compatibility
tested on 
	msys(git)
	osx
	linux

== Ref impl
clone
setup (make configs in user's home dir) add $host subfld
psetadd
padd
plist
pst
pgo
pstate


== Folder/file/content
.cfg-FOLDER
	<host1>-FOLDER
		default-FILE
			default_list=list1
		<list1>-FILE
			<prj_alias_1>
			<prj_alias_2>
		<list2>-FILE
			<prj_alias_2>
			<prj_alias_3>
		<prj_alias_1>-FILE
			path=msys_or_linux_path/to/root/dir/with/project
			type=git|svn|..
			remote_default=<default_remote_ex_origin>
			remote_extra=<extra_remote_ex_bitbucket>
			remote_extra=<extra_remote_ex_github>
		<prj_alias_2>-FILE
			...
		<prj_alias_3>-FILE
			...
	<host2>-FOLDER-FILE
		default-FILE
			<prj_alias_1>
			<prj_alias_2>
		<list1>-FILE
		<prj_alias_1>-FILE
			...
		<prj_alias_2>-FILE
			...
== Commands
  setup
  pcfg
pel		edit library (lib-prj)
padd		
pmove		
pren		

== Control
plist		[<list>]		list projects (from <the_host>.<list|default_list>): <alias>: home path
pst		
pstx		
pstate		gis

== Sync
pfix		
pget		
pgetall		
psave		
psaveall	
  psync		

== Navigate command
pgo		change dir to project home dir

== Misc
lib-prj		utility library
  p-help	cat readme.adoc
readme.adoc	the file
