:toc:
:toc-title:

= UTILS-PRJ

== What for

utils-prj is a set of shell scripts for:

	* rapid control for dozens of code projects in different contexts (personal, job, community, etc..)
		** define context - set of projects
		** define code project by alias, path and context 
		** switch context for bulk operations
		** execute bulk operation with set of projects or separate project by alias (such as review state, pull, fix, push or sync)
	* simple way to change current folder in console using project alias 

== Terms

*project* - pointer to project (path, repo type, etc.)

*set* - a group of projects (context), ex. in different context (ex job, my_utils, my_studies, etc.)

== Example

$ psetadd -cmn	# add set of projects

$ psw		# show all sets

$ padd prj1 	# add alias for current folder (code project)

$ cd $HOME	# move to any folder

$ plist 	# enlist current set

$ pst1		# show status of prj1 

$ pgo prj1	# change current path to prj1 home path

== Setup

=== Prerequisites (external tools)

	* git
	* coreutils
	* msys2 (Windows only) MSYS2 can't be installed on FAT* partitions or WinXP
	* gnu-sed (OSX only)

=== Recommendations 

	* ConEmu (Windows only)
	* utils-env - shell utility for print colored messages - https://github.com/bisoff/utils-env
	* utils-git - shell utility for work with git (to work with repository in simple manner) - https://github.com/bisoff/utils-git

=== How to install
	
	* osx
		** brew install coreutils
	* windows
		** download and install - https://sourceforge.net/projects/msys2/files/latest/download
		** pacman -Syu		# re-run console
		** pacman -S git	# if absent
	* shell
		$ cd <folder with utils>  # ex cd $HOME
		$ git clone https://github.com/bisoff/utils-prj.git
		$ cd utils-prj
		$ ./setup # it makes configs in user's home within <host_name> subfolder and default set of projects

=== How to uninstall

	$ uninstall-utils-prj


== Ref impl

	cd <project root path>
	padd p1		# add alias 'p1' for your project (and add pwd as projects path)
	plist		# to view your projects in current set (default)
	touch some_file # to make changes in project (it could be manipulation on any file)

	cd -		# change path to another
	pstate p1	# review status of project 'p1'
	pgo p1		# change path to projects path
	pstate .	# review status of current project
	pst		# to view status of all projects in current set (ex. you'll need to pull or push or add&commit you project)
	pfix . 		# add & commit your changes in local repository
	psave . 'ok'	# add, commit and push changes with massage 'ok'
	pget . 		# pull changes from remote

== Sync round

	psta		# view
	pgeta
	psavea
	psw set2
	psta

	psets
	psw
	plist
	pgo


== Command conventions

	next param used for:
	. - current project
	.. - all projects in set
	... - ovarall projects

== Folders / files / content

	.cfg-FOLDER
		<host1>-FOLDER
			default-FILE
				default_list=list1
			<list1>-FILE
				<prj_alias_1>
				<prj_alias_2>
			<list2>-FILE
				<prj_alias_2>
				<prj_alias_3>
			<prj_alias_1>-FILE
				path=msys_or_linux_path/to/root/dir/with/project
				type=git|svn|..
				remote_default=<default_remote_ex_origin>
				remote_extra=<extra_remote_ex_bitbucket>
				remote_extra=<extra_remote_ex_github>
			<prj_alias_2>-FILE
				...
			<prj_alias_3>-FILE
				...
		<host2>-FOLDER-FILE
			default-FILE
				<prj_alias_1>
				<prj_alias_2>
			<list1>-FILE
			<prj_alias_1>-FILE
				...
			<prj_alias_2>-FILE
				...

== Commands & major files

	$ p-help

